version: '3'

services:
  myapp:
    container_name: qr_generator
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DOMAIN=${DOMAIN}
      - DATABASE_NAME=${DATABASE_NAME}
    volumes:
      - ${DATA_DIR}:/app/${DATABASE_NAME}
